apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: auth-db
  namespace: url-shortener
spec:
  teamId: "url-shortener"
  volume:
    size: 5Gi
  numberOfInstances: 2
  users:
    postgres:  # superuser
    - superuser
    - createdb
  databases:
    auth: postgres
  postgresql:
    version: "16"
