apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: auth-redis
  namespace: url-shortener
spec:
  sentinel:
    replicas: 3
  redis:
    replicas: 3
    exporter:
      enabled: false
