services:
  # Expose Shortener service and its databases
  shortener:
    ports:
      - "8001:8001"

  shortener-db:
    ports:
      # Maps host port 5433 to container port 5432
      - "5433:5432"

  shortener-redis:
    ports:
      # Maps host port 6380 to container port 6379
      - "6380:6379"

  # Expose Auth service and its databases
  auth:
    ports:
      - "8002:8002"

  auth-db:
    ports:
      # Maps host port 5434 to container port 5432
      - "5434:5432"

  auth-redis:
    ports:
      # Maps host port 6381 to container port 6379
      - "6381:6379"
