apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: url-shortener-auth:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: url-shortener
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
